version: "3.8"

services:
  bot:
    build:
      context: ./TgBot
    container_name: bot

  chat:
    build:
      context: ./chat-ytb
    container_name: chat
    ports:
      - "3000:3000"

  neiro:
    build:
      context: ./face-swap
    container_name: neiro
    ports:
      - "5000:5000"
